// scripts/RESOURCE_LIST
import fs from "fs";
import path from "path";
import path2Type from "fhirpath/fhir-context/r4/path2Type.json";

const RESOURCES = Array.from(
    new Set(Object.keys(path2Type)
        .filter(key => key[0].toLowerCase() !== key[0])
        .map((key) => key.split(".")[0])
    ),
).sort();

const literalArray = `export const RESOURCE_TYPES = [\n${RESOURCES.map(
    (r) => `  "${r}"`,
).join(",\n")}\n] as const;\n`;

const output = `// Auto-generated by /scripts/RESOURCE_LIST.ts
// Do not edit manually

${literalArray}
`;

const targetPath = path.resolve("src/json.static.ts");

fs.writeFileSync(targetPath, output);
console.log("Successfully wrote RESOURCE_TYPES to src/json.static.ts");
