name = "medfetch"
main = "src/ingest.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "CLEAN_LOG"
database_name = "clean_log"
database_id = "YOUR_DATABASE_ID_HERE"  # Replace this with the UUID from the create command
migrations_dir = "migrations" 